# wrangler.toml
name = "workers-bot"
main = "./worker.js"
compatibility_date="2023-05-18"
compatibility_flags = [ "nodejs_compat" ]
kv_namespaces = [
  { binding = "LINK_CODES", id = "7a870e135ee34675b8065a1a60815363" }
]
[[d1_databases]]
binding = "DB"
database_name = "aliases-db"
database_id = "b51d611c-a31a-49e9-ae8a-a231618513e5"

[triggers]
routes = ["https://api.grab-tutorials.live/get-alias*"]